package com.alag.amall.business.module.order.server.mapper;

import com.alag.amall.business.module.order.api.model.Order;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_order
     *
     * @mbggenerated Thu Sep 05 21:08:34 CST 2019
     */
    int updateByPrimaryKey(Order record);

    Order selectByOrderNo(String orderNo);

    int updateOrderStatusByOrderNo(String orderNo);
}