package com.alag.amall.business.module.pay.server.mapper;

import com.alag.amall.business.module.pay.api.model.ResultPayInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ResultPayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    int insert(ResultPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    int insertSelective(ResultPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    ResultPayInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    int updateByPrimaryKeySelective(ResultPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amall_pay_info
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    int updateByPrimaryKey(ResultPayInfo record);

    ResultPayInfo selectByOrderNo(String orderNo);
}