package com.alag.amall.business.module.pay.api.model;

import java.io.Serializable;
import java.util.Date;

public class ResultPayInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.user_id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.order_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.trade_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.trade_status
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.gmt_payment
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private Date gmtPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.field1
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.field2
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amall_pay_info.field3
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    private String field3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.id
     *
     * @return the value of amall_pay_info.id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.id
     *
     * @param id the value for amall_pay_info.id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.user_id
     *
     * @return the value of amall_pay_info.user_id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.user_id
     *
     * @param userId the value for amall_pay_info.user_id
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.order_no
     *
     * @return the value of amall_pay_info.order_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.order_no
     *
     * @param orderNo the value for amall_pay_info.order_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.trade_no
     *
     * @return the value of amall_pay_info.trade_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.trade_no
     *
     * @param tradeNo the value for amall_pay_info.trade_no
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.trade_status
     *
     * @return the value of amall_pay_info.trade_status
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.trade_status
     *
     * @param tradeStatus the value for amall_pay_info.trade_status
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.gmt_payment
     *
     * @return the value of amall_pay_info.gmt_payment
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public Date getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.gmt_payment
     *
     * @param gmtPayment the value for amall_pay_info.gmt_payment
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setGmtPayment(Date gmtPayment) {
        this.gmtPayment = gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.field1
     *
     * @return the value of amall_pay_info.field1
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.field1
     *
     * @param field1 the value for amall_pay_info.field1
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.field2
     *
     * @return the value of amall_pay_info.field2
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.field2
     *
     * @param field2 the value for amall_pay_info.field2
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amall_pay_info.field3
     *
     * @return the value of amall_pay_info.field3
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amall_pay_info.field3
     *
     * @param field3 the value for amall_pay_info.field3
     *
     * @mbggenerated Thu Sep 05 17:12:39 CST 2019
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }
}